### ISSUE TITLE
Request fails if Tarantool returns any stirng longer then 31 byte

### ISSUE THREAD

**Issue by bogolt** [brigadier/tara#1]
Hello, when i request tarantool some data which includes strings all requests fails if string is longer then 31 byte. If request contains such a string i got reply:` {tara_response,0,66,error}`

I thought that the problem is with old msgpack version. 
I've tried to override specs to use new msgpack
`-define(MPACKOPTS, [{spec, new}, {map_format, jsx}]).`
However now all requests fail with: `{error,not_connected}`

I'm using Tarantool: 1.7.4

**Comment by brigadier** [comment]
Thanks for reporting, I'll have a look at this later today or tomorrow.

**Comment by brigadier** [comment]
I can't reproduce on 1.7.4-327-g8d0ea5870

Can you post structure of the space, with indexes and fields, and the tuple your code crash on?

**Comment by bogolt** [comment]
Tarantool db
```lua
#!/usr/bin/env tarantool

box.cfg {
	listen=3345,
	pid_file='xtarantool.pid',
	background=false,
	log = 'file:xtarantool.log',
	log_level=5
}

function get_s()
	return {'this is a long string, more then 31 byte'}
end

function get_small()
	return {'this is a short string'}
end

require('console').start()
```
Call it from erlang:
```erlang
    RespSmall = tara:call(tarantool_conn_pool_0, <<"get_small">>, []),
    error_logger:info_msg("Resp: ~p", [RespSmall]),

    RespBig = tara:call(tarantool_conn_pool_0, <<"get_s">>, []),
    error_logger:info_msg("Resp: ~p", [RespBig]),

```

Result:
```
Resp: {tara_response,0,66,[{48,[[<<"this is a short string">>]]}]}
Resp: {tara_response,0,66,error}
```

**Comment by brigadier** [comment]
Fixed. Please checkout v0.12

**Comment by bogolt** [comment]
Thank You, works great now!
